routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TwoFactorController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified', '2fa'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/secret', [TwoFactorController::class, 'secret'])->name('2fa.secret');
    Route::post('/secret', [TwoFactorController::class, 'secret_save'])->name('2fa.secret_save');
    Route::get('/auth', [TwoFactorController::class, 'auth'])->name('2fa.auth');
    Route::get('/check/{id}', [TwoFactorController::class, 'check'])->name('2fa.check');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::get('/denied', [TwoFactorController::class, 'denied'])->name('2fa.denied');

Route::get('/test', [TestController::class, 'index']);

require __DIR__.'/auth.php';

app/Http/Controllers/TwoFactorController.php
<?php

namespace App\Http\Controllers;

use App\AuthReq as AppAuthReq;
use App\Http\Requests\ProfileUpdateRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

use App\Models\User;
use App\Models\AuthReq;

class TwoFactorController extends Controller
{
    /**
     * Display the user's profile form.
     */
    public function auth(Request $request)
    {
        if(empty(Auth::user()->secret)) {
            return Redirect::route('2fa.secret');
        }
        if(!empty(Auth::user()->auth) && now() < Auth::user()->auth) {
            return Redirect::route('dashboard');
        }

        $auth = AuthReq::where('user_id', Auth::user()->id)->first();
        if(isset($auth) && $auth->valid_until < now()) {
            return Redirect::route('2fa.denied');
        }
        if(!isset($auth)) {
            AuthReq::where('user_id', Auth::user()->id)->delete();
            AuthReq::create([
                'user_id' => Auth::user()->id,
                'valid_until' => now()->addMinutes(10),
            ]);
        }

        return view('twofactor.auth');
    }

    public function secret(Request $request)
    {
        if(!empty(Auth::user()->secret)) {
            return Redirect::route('dashboard');
        }
        $secret = bin2hex(openssl_random_pseudo_bytes(4));
        return view('twofactor.secret', [
            'secret' => $secret,
        ]);
    }

    public function secret_save(Request $request)
    {
        $validate = $request->validate([
            'secret' => ['required'],
        ]);
        $user = User::findOrFail(Auth::user()->id);
        $user->secret = Hash::make($validate['secret']);
        $user->save();
        return Redirect::route('2fa.auth');
    }

    public function authReq(Request $request)
    {
        $all = $request->all();
        if(empty($all['secret']) || empty($all['user_email'])) {
            return response()->json([
                'secret' => $all['secret']??'null',
                'user_email' => $all['user_email']??'null',
            ], 422);
        } else {
            $user = User::where('email', $all['user_email'])->firstOrFail();
            if(Hash::check($all['secret'], $user->secret)) {
                $auth = AuthReq::where('user_id', $user->id)->first();
                if(empty($auth)) return response()->json(['request' => false], 200);
                if($auth->valid_until < now()) {
                    // dd($auth);
                    $auth->delete();
                } else {
                    return response()->json(['request' => true], 200);
                }
                return response()->json(['request' => false], 200);
            } else {
                return response()->json(['Access denied'], 403);
            }
        }
    }

    public function authCheck(Request $request)
    {
        $all = $request->all();
        if(empty($all['secret']) || empty($all['user_email']) || empty($all['response'])) {
            return response()->json([
                'secret' => $all['secret']??'null',
                'user_email' => $all['user_email']??'null',
                'response' => $all['response']??'null',
            ], 422);
        } else {
            $user = User::where('email', $all['user_email'])->firstOrFail();
            if(Hash::check($all['secret'], $user->secret)) {
                $auth = AuthReq::where('user_id', $user->id)->first();
                if(empty($auth)) return response()->json(['request' => false], 422);
                if($auth->valid_until < now() || $all['response'] == "false") {
                    // dd($auth);
                    $auth->valid_until = now();
                    $auth->save();
                    return response()->json(['denied' => true], 200);
                } else if($all['response'] == "true") {
                    $auth->delete();
                    $user->auth = now()->addMinutes(2);
                    $user->save();
                    return response()->json(['accepted' => true], 200);
                }
            } else {
                return response()->json(['Access denied'], 403);
            }
        }
    }

    public function check(Request $request, $id)
    {
        $user = User::find($id);
        if($user && !empty($user->auth) && now() < $user->auth) {
            return response()->json(['redirect' => route('dashboard')]);
        } else if(empty($user->authReq) || $user->authReq->valid_until < now()) {
            return response()->json(['redirect' => route('2fa.denied')]);
        } else {
            return response()->json([]);
        }
    }

    public function denied(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();
        return view('twofactor.denied');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/twofactor/auth.blade.php
<x-guest-layout>
    {{-- <form method="POST" action="{{ route('register') }}">
        @csrf

        <h2 class="text-base font-semibold leading-7 text-gray-900">2 Factor Authentification</h2>

        <div class="relative pt-1">
            <div class="overflow-hidden h-2 mb-4 text-xs flex rounded bg-slate-200">
              <div style="width:30%" class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-slate-500"></div>
            </div>
          </div>

        <div class="flex items-center justify-end mt-4">
            <a class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" href="{{ route('login') }}">
                {{ __('Already registered?') }}
            </a>

            <x-primary-button class="ml-4">
                {{ __('Register') }}
            </x-primary-button>
        </div>
    </form> --}}
            {{-- <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6"> --}}
              <div>
                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-yellow-100">
                  <svg class="h-6 w-6 text-yellow-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div class="mt-3 text-center sm:mt-5">
                  <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">2FA Request</h3>
                  <div class="mt-2">
                    <p class="text-sm text-gray-500">Please check your smartwatch to accept the request.</p>
                  </div>
                </div>
              </div>
              {{-- <div class="mt-5 sm:mt-6">
                <button type="button" class="inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Resend 2FA request</button>
              </div> --}}
              <div x-data="{
                redirectUrl: '',
                checkForUpdates() {
                    fetch('/check/{{ Auth::user()->id }}')
                        .then(response => response.json())
                        .then(data => {
                            if (data.redirect) {
                                window.location.href  = data.redirect;
                            } else {
                                setTimeout(() => this.checkForUpdates(), 10000); // Poll again after 1 second
                            }
                        })
                        .catch(() => {
                            setTimeout(() => this.checkForUpdates(), 10000); // Retry after 1 second if there was an error
                        });
                },
                redirectToUrl() {
                    if (this.redirectUrl) {
                        window.location.href = this.redirectUrl;
                    }
                }
            }" x-init="checkForUpdates()">
            </div>
</x-guest-layout>

resources/views/twofactor/denied.blade.php
<x-guest-layout>
    <div>
        <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-red-100">
            <svg class="h-6 w-6 text-red-600"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 stroke="currentColor"
                 aria-hidden="true">
                 <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>

        </div>
        <div class="mt-3 text-center sm:mt-5">
            <h3 class="text-base font-semibold leading-6 text-gray-900"
                id="modal-title">2FA Request denied</h3>
            <div class="mt-2">
                <p class="text-sm text-gray-500">Your request has been denied or is no longer valid. You have been logged out and you can try again later.</p>
            </div>
        </div>
    </div>
    <div class="mt-5 sm:mt-6">
        <a href="{{route('index')}}" class="inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
            Take me back to the website
        </a>
    </div>
</x-guest-layout>

resources/views/twofactor/secret.blade.php
<x-guest-layout>
    <form method="POST" action="{{ route('2fa.secret_save') }}">
        @csrf

            {{-- <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6"> --}}
              <div>
                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-yellow-100">
                  <svg class="h-6 w-6 text-yellow-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
                  </svg>

                </div>
                <div class="mt-3 text-center sm:mt-5">
                  <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">2FA Secret</h3>
                  <div class="mt-2">
                    <p class="text-sm text-gray-500">Please enter this secret in the 2FA App tp connect your smartwatch safely with our service.</p>
                  </div>
                  <div class="mt-2">
                    <p class="text-xl text-gray-900">{{ $secret }}</p>
                    <input class="hidden" name="secret" value="{{ $secret }}">
                  </div>
                </div>
              </div>
              <div class="mt-5 sm:mt-6">
                <button type="submit" class="inline-flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    I have saved this secret and want to continue
                </button>
              </div>
            </form>
</x-guest-layout>